# Generated by Django 4.1.5 on 2023-02-03 13:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('time_tracker', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_name', models.CharField(max_length=200, verbose_name='Client Name')),
            ],
            options={
                'verbose_name': 'Client',
                'verbose_name_plural': 'Clients',
                'db_table': 'clients',
            },
        ),
        migrations.AddField(
            model_name='task',
            name='comments',
            field=models.CharField(max_length=300, null=True, verbose_name='Comments'),
        ),
        migrations.AddField(
            model_name='task',
            name='status',
            field=models.CharField(choices=[('Approved', 'Approved'), ('Declined', 'Declined')], default='Approved', max_length=300, verbose_name='Status'),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='ClientUsers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_type', models.CharField(choices=[('Manager', 'Manager'), ('Approver', 'Approver')], max_length=100)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='users', to='time_tracker.client')),
            ],
            options={
                'verbose_name': 'ClientUser',
                'verbose_name_plural': 'ClientUsers',
                'db_table': 'client_users',
            },
        ),
    ]
