# Generated by Django 4.1.5 on 2023-02-03 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('time_tracker', '0002_client_task_comments_task_status_clientusers'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='comments',
        ),
        migrations.RemoveField(
            model_name='task',
            name='status',
        ),
        migrations.AddField(
            model_name='timetrack',
            name='comments',
            field=models.CharField(max_length=300, null=True, verbose_name='Comments'),
        ),
        migrations.AddField(
            model_name='timetrack',
            name='status',
            field=models.CharField(choices=[('Approved', 'Approved'), ('Declined', 'Declined')], default='Approved', max_length=300, verbose_name='Status'),
            preserve_default=False,
        ),
    ]
