# Generated by Django 4.1.5 on 2023-02-03 13:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('time_tracker', '0003_remove_task_comments_remove_task_status_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TimeTrackData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comments', models.CharField(max_length=300, null=True, verbose_name='Comments')),
                ('client_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='time_track_data', to='time_tracker.clientusers')),
                ('time_track', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='time_track_data', to='time_tracker.timetrack')),
            ],
            options={
                'verbose_name': 'TimeTrackData',
                'verbose_name_plural': 'TimeTrackData',
                'db_table': 'time_track_data',
            },
        ),
    ]
