# Generated by Django 4.1.5 on 2023-02-03 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('time_tracker', '0005_clientusers_user_alter_clientusers_client'),
    ]

    operations = [
        migrations.AddField(
            model_name='timetrackdata',
            name='status',
            field=models.CharField(choices=[('Approved', 'Approved'), ('Declined', 'Declined')], default='Approved', max_length=300, verbose_name='Status'),
            preserve_default=False,
        ),
    ]
