# Generated by Django 4.1.5 on 2023-02-03 14:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('time_tracker', '0006_timetrackdata_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='client',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='client', to='time_tracker.client'),
            preserve_default=False,
        ),
    ]
