# Generated by Django 4.1.5 on 2023-02-03 14:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('time_tracker', '0007_project_client'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='clientusers',
            table='clientusers',
        ),
    ]
